config/routes.rb
Rails.application.routes.draw do
  resources :hikes do
    member do
      match 'subscribe', to: 'hikes#subscribe', via: %i[get post delete]
    end
    resources :hike_cars, shallow: true, except: %i[index] do
      resources :hike_participants, shallow: true, except: %i[index]
    end
  end
  get 'hike_details' => 'hikes#hike_details', as: :get_hike_details

  resource :user, except: %i[new create] do
    resource :waiver, only: %i[new create show]
    resource :session, only: %i[new create update destroy]
  end
  resolve('User') { [:user] }

  scope :user do
    resources :cars, except: %i[index]
  end

  get 'auth/google_oauth2/callback' => 'sessions#create'
  get 'help' => 'static#help'
  get "up" => "rails/health#show", as: :rails_health_check

  root "dashboard#index"
end

app/models/hike_participant.rb
class HikeParticipant < ApplicationRecord
  belongs_to :hike_car
  belongs_to :user
  store :metadata, accessors: %i[note], coder: JSON
end

app/controllers/hike_participants_controller.rb
class HikeParticipantsController < ApplicationController
  before_action :set_hike_car, only: %i[new create]
  before_action :set_hike_participant, only: %i[show edit update destroy]

  def show
  end

  def new
    @can_participate = @hike_car.spot_available? &&
                       !@user.hike_participant?(@hike_car.hike) &&
                       !@user.hike_driver?(@hike_car.hike)
    @hike_participant = @hike_car.participants.new if @can_participate
  end

  def edit
  end

  def create
    unless @hike_car.spot_available?
      redirect_to @hike_car.hike, alert: "No spots available in the car"
      return
    end
    @hike_participant = @hike_car.participants.create!(hike_participant_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @hike, notice: "Successfully joined the hike" }
    end
  end

  def update
    if @hike_participant.update(hike_participant_params)
      redirect_to hike_participant_url(@hike_participant)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @hike_participant.destroy!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @hike, notice: "Successfully left the hike" }
    end
  end

  private

  def set_hike_car
    @hike_car = HikeCar.find(params[:hike_car_id])
  end

  def set_hike_participant
    @hike_participant = HikeParticipant.find(params[:id])
  end

  def hike_participant_params
    params.require(:hike_participant).permit(:hike_car_id, :user_id, :note)
  end
end

app/views/hike_participants/_form.html.erb
<%= form_with model: [ @hike_car, @hike_participant ], class: "px-4 grid grid-cols-2 xl:grid-cols-4" do |form| %>
  <div class="py-2 flex justify-center gap-3 items-center">
    <%= render "avatar", user: @user %>
    <div>
      <div class="text-gray-700"><%= @user.preferred_name.present? ? @user.preferred_name : @user.full_name %></div>
      <div class="text-gray-400"><%= number_to_phone(@user.phone_no, area_code: true) %></div>
    </div>
  </div>
  <div class="py-2 col-span-1 xl:col-span-2 flex justify-center gap-3 items-center">
    <%= form.text_area :note, placeholder: "Note for the driver", class:"w-full rounded-md border-gray-300 shadow-sm focus:border-primary-400 focus:ring focus:ring-primary-200 focus:ring-opacity-50 disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500 text-sm" %>
  </div>
  <%= form.hidden_field :user_id, value: @user.id %>
  <div class="py-2 col-start-2 xl:col-start-4 flex justify-center items-center">
    <% if edit %>
      <%= form.submit "Update", class: "h-12 rounded-lg px-2 bg-gray-500 hover:bg-gray-600 text-white cursor-pointer" %>
    <% else %>
      <%= form.submit "Join hike", class: "h-12 rounded-lg px-2 bg-blue-500 hover:bg-blue-600 text-white cursor-pointer" %>
    <% end %>
  </div>
<% end %>

app/views/hike_participants/_hike_participant.html.erb
<%= turbo_frame_tag dom_id(hike_participant) do %>
  <div class="px-4 relative grid grid-cols-2 xl:grid-cols-4">
    <div class="py-2 flex justify-center gap-3 items-center">
      <div class="flex-shrink-0">
        <%= render "avatar", user: hike_participant.user %>
      </div>
      <div class="flex flex-col items-center w-full">
        <div class="text-gray-700"><%= hike_participant.user.preferred_name.present? ? hike_participant.user.preferred_name : hike_participant.user.full_name %></div>
      </div>
    </div>
    <div class="py-2 flex justify-center items-center">
      <div>
        <%= link_to number_to_phone(hike_participant.user.phone_no, area_code: true), "tel:#{hike_participant.user.phone_no}", class: "text-primary-500 text-sm"  %>
        <div class="text-gray-400 text-sm"><%= hike_participant.user.discord %></div>
      </div>
    </div>
    <% if hike_participant.note.present? %>
      <div class="py-2 col-span-2 flex justify-center items-center">
        <div class="text-gray-700"><%= hike_participant.note %></div>
      </div>
    <% end %>
    <div class="absolute right-4 top-3 py-2">
      <div class="flex gap-1">
        <% if @user == hike_participant.user %>
          <%= link_to edit_hike_participant_path(hike_participant), "x-data":"{ tooltip: 'Edit' }" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="blue" class="h-5 w-5 cursor-pointer text-secondary-500" x-tooltip="tooltip">
              <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
            </svg>
          <% end %>
        <% end %>
        <% if @user.car_driver?(hike_participant.hike_car) || @user.admin? || @user == hike_participant.user %>
          <%= link_to hike_participant_path(hike_participant), data: {turbo_method: :delete, turbo_frame: "_top", turbo_confirm: "Are you sure you want to leave the hike?"}, "x-data":"{ tooltip: 'Delete' }" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="red" class="h-5 w-5 cursor-pointer text-secondary-500" x-tooltip="tooltip">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
            </svg>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/hike_participants/create.turbo_stream.erb
<%= turbo_stream.append dom_id(@hike_car) + "_participants", @hike_participant %>
<% for hike_car in @hike_car.hike.hike_cars %>
  <%= turbo_stream.update "new_" + dom_id(hike_car) + "_participant", "" %>
<% end %>

app/views/hike_participants/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@hike_participant) %>
<% for hike_car in @hike_participant.hike_car.hike.hike_cars %>
  <%= turbo_stream.replace "new_" + dom_id(hike_car) + "_participant" do %>
    <%= turbo_frame_tag "new_" + dom_id(hike_car) + "_participant", src: new_hike_car_hike_participant_path(@hike_participant.hike_car), target: "_top" %>
  <% end %>
<% end %>

app/views/hike_participants/edit.html.erb
<%= turbo_frame_tag dom_id(@hike_participant) do %>
  <%= render "form", hike_participant: @hike_participant, edit: true %>
<% end %>

app/views/hike_participants/new.html.erb
<%= turbo_frame_tag "new_" + dom_id(@hike_car) + "_participant", target: "_top" do %>
  <% if @can_participate %>
    <%= render "form", hike_participant: @hike_participant, edit: false %>
  <% end %>
<% end %>

app/views/hike_participants/show.html.erb
<%= render "hike_participants/hike_participant", hike_participant: @hike_participant %>