config/routes.rb
Rails.application.routes.draw do
  resources :hikes do
    member do
      match 'subscribe', to: 'hikes#subscribe', via: %i[get post delete]
    end
    resources :hike_cars, shallow: true, except: %i[index] do
      resources :hike_participants, shallow: true, except: %i[index]
    end
  end
  get 'hike_details' => 'hikes#hike_details', as: :get_hike_details

  resource :user, except: %i[new create] do
    resource :waiver, only: %i[new create show]
    resource :session, only: %i[new create update destroy]
  end
  resolve('User') { [:user] }

  scope :user do
    resources :cars, except: %i[index]
  end

  get 'auth/google_oauth2/callback' => 'sessions#create'
  get 'help' => 'static#help'
  get "up" => "rails/health#show", as: :rails_health_check

  root "dashboard#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sessions, dependent: :destroy
  has_many :waivers, dependent: :destroy
  has_many :cars, dependent: :destroy
  has_many :hikes, foreign_key: :host_id, dependent: :destroy
  has_many :hike_cars, through: :cars
  validates :email, presence: true, uniqueness: true
  validates :phone_no, presence: true, format: { with: /\A\d{10}\z/ }, on: :update

  def self.create_from_omniauth(auth)
    user = find_by(email: auth.info.email)
    first_time = user.nil?
    roles = email_verified?(auth.info.email) ? ["hiker"] : []
    user ||= create(email: auth.info.email, full_name: auth.info.name, avatar_url: auth.info.image, roles:)
    if user.avatar_url.nil?
      update(user.id, email: auth.info.email, full_name: auth.info.name,
                      avatar_url: auth.info.image)
    end
    [user, first_time]
  end

  def admin?
    roles.include?("board")
  end

  def hiker?
    roles.include?("hiker")
  end

  def host?(hike)
    id == hike.host.id
  end

  def self.email_verified?(p_email)
    p_email.ends_with?("ucsd.edu") || p_email.ends_with?("ucsd.com")
  end

  def allowed_site_access?
    self.class.email_verified?(email) || hiker?
  end

  def car_participant?(hike_car)
    hike_car.participants.exists?(user_id: id)
  end

  def hike_participant?(hike)
    hike.hike_participants.exists?(user_id: id)
  end

  def car_driver?(hike_car)
    hike_car.car.user_id == id
  end

  def hike_driver?(hike)
    hike.hike_cars.exists?(car_id: cars.ids)
  end

  def subscribed?(hike)
    hike.subscribers.include?(id)
  end

  def allowed_notifications?
    sessions.any? { |session| session.push_endpoint.present? }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :added_phone_number!

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Profile was successfully updated"
    else
      render :edit, status: :unprocessable_entity, alert: "Profile could not be updated"
    end
  end

  def destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:preferred_name, :phone_no, :discord)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<p class="my-2">
  <strong class="font-medium">Email</strong>
  <div class="w-full rounded-lg border border-gray-200 p-4 pe-12 text-sm shadow-sm">
    <%= @user.email %>
  </div>
</p>
<p class="my-2">
  <strong class="font-medium">Full name</strong>
  <div class="w-full rounded-lg border border-gray-200 p-4 pe-12 text-sm shadow-sm">
    <%= @user.full_name %>
  </div>
</p>
<p class="my-2">
  <strong class="font-medium">Preferred name</strong>
  <div class="w-full rounded-lg border border-gray-200 p-4 pe-12 text-sm shadow-sm">
    <%= @user.preferred_name %>
  </div>
</p>
<p class="my-2">
  <strong class="font-medium">Phone number</strong>
  <div class="w-full rounded-lg border border-gray-200 p-4 pe-12 text-sm shadow-sm">
    <%= @user.phone_no %>
  </div>
</p>
<p class="my-2">
  <strong class="font-medium">Discord username</strong>
  <div class="w-full rounded-lg border border-gray-200 p-4 pe-12 text-sm shadow-sm">
    <%= @user.discord %>
  </div>
</p>

app/views/users/edit.html.erb
<div class="mx-auto max-w-screen-xl px-4 py-16 sm:px-6 lg:px-8">
  <%= turbo_frame_tag "user" do %>
    <%= form_with(model: @user, data: { turbo_frame: "_top" }, local: true) do |form| %>
      <p class="my-5">
        <%= form.label :email, class: "font-medium" %>
        <span class="place-content-center text-red-700">*</span>
        <div class="w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm">
          <%= @user.email %>
        </div>
      </p>
      <p class="my-5">
        <%= form.label :full_name, class: "font-medium" %>
        <span class="place-content-center text-red-700">*</span>
        <div class="w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm">
          <%= @user.full_name %>
        </div>
      </p>
      <p class="my-5">
        <%= form.label :preferred_name, class: "font-medium" %>
        <%= form.text_field :preferred_name, class:"w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm" %>
      </p>
      <p class="my-5">
        <div class="relative">
          <%= form.label :phone_no, "Phone number", class: "font-medium" %>
          <% @user.errors.full_messages_for(:phone_no).each do |message| %>
            <span class="place-content-center text-red-700 text-sm"><%= message %></span>
          <% end %>
          <span class="place-content-center text-red-700">*</span>
        </div>
        <%= form.phone_field :phone_no, class:"w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm", pattern:"[0-9]{10}", placeholder:"1234567890" %>
      </p>
      <p class="my-5">
        <%= form.label :discord, "Discord username", class: "font-medium" %>
        <%= form.text_field :discord, class:"w-full rounded-lg border-gray-200 p-4 pe-12 text-sm shadow-sm" %>
      </p>
      <div class="relative">
        <%= form.submit class:"mt-6 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
        <%= link_to "Delete profile", user_path, data: {turbo_method: :delete, turbo_frame: "_top", turbo_confirm: "Are you sure you want to delete your profile?"}, class: "inline-block ml-2 mt-6 rounded-lg py-3 px-5 bg-red-100 hover:bg-red-200 font-medium" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="flex flex-wrap items-stretch justify-center my-4">
  <div class="w-full min-h-96 h-full lg:w-2/5 mx-2 my-2 rounded-lg p-6 shadow-lg">
    <h1 class="font-bold text-2xl">Profile</h1>
    <%= turbo_frame_tag "user" do %>
      <%= render @user %>
      <%= link_to "Edit profile", edit_user_path, class: "mt-6 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
    <% end %>
  </div>
  <div class="relative min-h-36 w-full lg:w-2/5 mx-2 my-2 rounded-lg p-6 shadow-lg">
    <h1 class="font-bold text-2xl">Cars</h1>
    <div id="cars" class="w-full">
      <%= render @user.cars %>
    </div>
    <%= turbo_frame_tag "new_car", class: "flex min-h-16" do %>
      <%= link_to "Add car", new_car_path, class: "absolute bottom-6 left-6 mt-2 rounded-lg py-3 px-5 bg-blue-500 hover:bg-blue-600 text-white inline-block font-medium" %>
    <% end %>
  </div>
</div>