config/routes.rb
Rails.application.routes.draw do
  resources :hikes do
    member do
      match 'subscribe', to: 'hikes#subscribe', via: %i[get post delete]
    end
    resources :hike_cars, shallow: true, except: %i[index] do
      resources :hike_participants, shallow: true, except: %i[index]
    end
  end
  get 'hike_details' => 'hikes#hike_details', as: :get_hike_details

  resource :user, except: %i[new create] do
    resource :waiver, only: %i[new create show]
    resource :session, only: %i[new create update destroy]
  end
  resolve('User') { [:user] }

  scope :user do
    resources :cars, except: %i[index]
  end

  get 'auth/google_oauth2/callback' => 'sessions#create'
  get 'help' => 'static#help'
  get "up" => "rails/health#show", as: :rails_health_check

  root "dashboard#index"
end

app/models/hike.rb
class Hike < ApplicationRecord
  belongs_to :host, class_name: 'User'
  has_many :hike_cars, dependent: :destroy
  has_many :hike_participants, through: :hike_cars, source: :participants
  has_one_attached :graphic
  store :stats, accessors: %i[length elevation duration route_type difficulty], coder: JSON

  validates :title, :length, :elevation, :duration, :route_type, :difficulty, :description, :date,
            :time, :trailhead_address, :suggested_items, presence: true, unless: :draft?

  validates :short_description, :graphic, presence: true, if: :published?

  def date
    datetime&.to_date&.strftime('%B %d %A') || 'No date'
  end

  def time
    datetime&.strftime('%I:%M %p') || 'No time'
  end

  def published?
    status == 'published'
  end

  def draft?
    status == 'draft'
  end

  def review?
    status == 'review'
  end
end

app/controllers/hikes_controller.rb
require 'net/http'
require 'uri'

class HikesController < ApplicationController
  before_action :set_hike, only: %i[show edit update destroy subscribe]
  after_action :admin_review_notification, only: %i[create update]

  DIFFICULTY_MAPPING = {
    1 => 'Easy',
    2 => 'Easy-Moderate',
    3 => 'Moderate',
    4 => 'Moderate-Hard',
    5 => 'Hard'
  }.freeze

  def index
    @upcoming_hikes = Hike.where(status: 'published').where('datetime >= ?', Date.today).order(datetime: :asc)
    @past_hikes = Hike.where(status: 'published').where('datetime < ?', Date.today).order(datetime: :desc)
    @pagy, @past_hikes = pagy(@past_hikes, items: 3)
  end

  def show
  end

  def new
    @hike = Hike.new
    hike_notification
  end

  def edit
  end

  def create
    @hike = Hike.new(hike_params.except(:graphic))
    @hike.host_id = @user.id
    handle_graphic

    if @hike.save
      redirect_to hike_url(@hike), notice: "Hike was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    handle_graphic
    was_draft = @hike.status == 'draft'

    if @hike.update(hike_params.except(:graphic))
      hike_notification if was_draft && @hike.status == 'published'
      redirect_to hike_url(@hike), notice: "Hike was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @hike.destroy!
    redirect_to root_path, notice: "Hike was successfully deleted."
  end

  def hike_details
    alltrails_link = params[:alltrails_link].strip.split('?').first
    hike_details = CA_HIKE_MAP[alltrails_link]
    title = hike_details['trail_name']
    title = "#{title} (@#{hike_details['area']})" if hike_details['area'].present?
    render json: hike_details.slice('length', 'elevation', 'duration', 'route_type', 'difficulty').merge(title:)
  end

  def subscribe
    case request.method_symbol
    when :post
      if params[:_method] == 'delete'
        @hike.subscribers.delete(@user.id)
      elsif @hike.subscribers.exclude?(@user.id)
        @hike.subscribers << @user.id
      end
      @hike.save
    end
    render partial: 'subscription', locals: { hike: @hike }
  end

  private

  def get_full_url(short_url)
    uri = URI.parse(short_url)
    response = Net::HTTP.get_response(uri)
    return response['location'] if response.code == '302'

    short_url
  end

  def handle_graphic
    return unless hike_params[:graphic].present?

    graphic = "#{@hike.datetime}_#{hike_params[:graphic].original_filename}"
    key = "graphics/#{graphic}"

    blob = ActiveStorage::Blob.find_by(key:)

    blob ||= ActiveStorage::Blob.create_and_upload!(
      io: hike_params[:graphic].open,
      filename: graphic,
      key:
    )

    @hike.graphic.attach(blob)
  end

  def set_hike
    @hike = Hike.find(params[:id])
  end

  def hike_params
    permitted = params.require(:hike).permit(:alltrails_link, :length, :elevation, :duration, :route_type, :difficulty,
                                             :driver_compensation_type, :title, :description, :date, :time,
                                             :trailhead_address, :suggested_items, :notes, :status, :graphic,
                                             :short_description, :metadata, :datetime, :hike_type)
    if permitted[:date].present? && permitted[:time].present?
      permitted[:datetime] =
        "#{permitted[:date]} #{permitted[:time]}".in_time_zone('Pacific Time (US & Canada)').to_datetime
    end
    if permitted[:trailhead_address].present?
      permitted[:trailhead_address] = get_full_url(permitted[:trailhead_address])
    end
    permitted.except(:date, :time)
  end

  def hike_notification
    return unless @hike.published?

    title = "New hike posted! #{@hike.title}"
    body = @hike.short_description
    icon = @hike.graphic.attached? ? url_for(@hike.graphic) : '/assets/hiking_logo.svg'
    link = hike_url(@hike)

    notify_users(User.all, title, body, icon, link)
  end

  def admin_review_notification
    return unless @hike.review?

    title = 'New hike for review'
    body = @hike.title
    icon = @hike.graphic.attached? ? url_for(@hike.graphic) : '/assets/hiking_logo.svg'
    link = hike_url(@hike)

    notify_users(User.all.select(&:admin?), title, body, icon, link)
  end
end

app/helpers/hikes_helper.rb
module HikesHelper
end

app/views/hikes/_form.html.erb
<%= form_with(model: hike, class: "mt-4 md:grid md:grid-cols-2 md:gap-y-6 md:gap-x-8", local: true, data: { controller: "hike" }) do |form| %>
  <div class="col-span-2">
    <div class="flex">
      <%= form.label :alltrails_link, "Alltrails link", class: "mr-1" %>
      <span class="place-content-center text-red-700 mr-2">*</span>
      <% if @hike.errors[:alltrails_link].any? %>
        <span class="text-red-500"><%= @hike.errors[:alltrails_link].join(", ") %></span>
      <% end %>
    </div>
    <%= form.text_field :alltrails_link, "data-hike-target": "alltrailsLink", placeholder: "Inserting link autofills trail stats below (click out of the box to update stats)", class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div>
    <div class="flex">
      <%= form.label :length, "Length (in miles)", class: "mr-2" %>
      <% if @hike.errors[:length].any? %>
        <span class="text-red-500"><%= @hike.errors[:length].join(", ") %></span>
      <% end %>
    </div>
    <%= form.text_field :length, "data-hike-target": "length", class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div>
    <div class="flex">
      <%= form.label :elevation, "Elevation (in feet)", class: "mr-2" %>
      <% if @hike.errors[:elevation].any? %>
        <span class="text-red-500"><%= @hike.errors[:elevation].join(", ") %></span>
      <% end %>
    </div>
    <%= form.number_field :elevation, "data-hike-target": "elevation", class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div>
    <div class="flex">
      <%= form.label :route_type, "Route type", class: "mr-2" %>
      <% if @hike.errors[:route_type].any? %>
        <span class="text-red-500"><%= @hike.errors[:route_type].join(", ") %></span>
      <% end %>
    </div>
    <%= form.text_field :route_type, "data-hike-target": "routeType", class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div>
    <div class="flex">
      <%= form.label :duration, "Duration (in mins)", class: "mr-2" %>
      <% if @hike.errors[:duration].any? %>
        <span class="text-red-500"><%= @hike.errors[:duration].join(", ") %></span>
      <% end %>
    </div>
    <%= form.number_field :duration, "data-hike-target": "duration", class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div>
    <div class="flex">
      <%= form.label :difficulty, "Difficulty", class: "mr-2" %>
      <% if @hike.errors[:difficulty].any? %>
        <span class="text-red-500"><%= @hike.errors[:difficulty].join(", ") %></span>
      <% end %>
    </div>
    <%= form.select :difficulty, options_for_select(HikesController::DIFFICULTY_MAPPING.invert, @hike.difficulty), {}, { "data-hike-target": "difficulty", class: "shadow rounded-md border border-gray-200 w-full"} %>
  </div>
  <div class="grid grid-cols-2 gap-4">
    <div>
      <div class="flex">
        <%= form.label :driver_compensation_type, "Driver compensation", class: "mr-2" %>
        <% if @hike.errors[:driver_compensation_type].any? %>
          <span class="text-red-500"><%= @hike.errors[:driver_compensation_type].join(", ") %></span>
        <% end %>
      </div>
      <div>
        <%= form.select :driver_compensation_type, ["UCSD rate", "Manual rate"], "data-hike-target": "driverComp", class: "shadow rounded-md border border-gray-200 w-full" %>
      </div>
    </div>
    <% if @user.admin? %>
      <div>
        <div class="flex">
          <%= form.label :hike_type, "Hike Type", class: "mr-2" %>
          <% if @hike.errors[:hike_type].any? %>
            <span class="text-red-500"><%= @hike.errors[:hike_type].join(", ") %></span>
          <% end %>
        </div>
        <div>
          <%= form.select :hike_type, ["official", "colab", "community"], class: "shadow rounded-md border border-gray-200 w-full" %>
        </div>
      </div>
    <% else %>
      <%= form.hidden_field :hike_type, value: "community" %>
    <% end %>
  </div>
  <div class="col-span-2">
    <div class="flex">
      <%= form.label :title, class: "mr-1" %>
      <span class="place-content-center text-red-700 mr-2">*</span>
      <% if @hike.errors[:title].any? %>
        <span class="text-red-500"><%= @hike.errors[:title].join(", ") %></span>
      <% end %>
    </div>
    <%= form.text_field :title, "data-hike-target": "title", class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div class="col-span-2 row-span-3">
    <div class="flex">
      <%= form.label :description, class: "mr-2" %>
      <% if @hike.errors[:description].any? %>
        <span class="text-red-500"><%= @hike.errors[:description].join(", ") %></span>
      <% end %>
    </div>
    <%= form.text_area :description, placeholder: "Full description of the hike (including instructions)", class: "shadow rounded-md border border-gray-200 w-full min-h-64" %>
  </div>
  <div>
    <div class="flex">
      <%= form.label :date, class: "mr-1" %>
      <span class="place-content-center text-red-700 mr-2">*</span>
      <% if @hike.errors[:date].any? %>
        <span class="text-red-500"><%= @hike.errors[:date].join(", ") %></span>
      <% end %>
    </div>
    <%= form.date_field :date, value: @hike.datetime&.strftime('%Y-%m-%d'), class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div>
    <div class="flex">
      <%= form.label :time, class: "mr-1" %>
      <span class="place-content-center text-red-700 mr-2">*</span>
      <% if @hike.errors[:time].any? %>
        <span class="text-red-500"><%= @hike.errors[:time].join(", ") %></span>
      <% end %>
    </div>
    <%= form.time_field :time, value: @hike.datetime&.strftime('%H:%M'), include_seconds: false, class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div class="col-span-2">
    <div class="flex">
      <%= form.label :trailhead_address, class: "mr-2" %>
      <% if @hike.errors[:trailhead_address].any? %>
        <span class="text-red-500"><%= @hike.errors[:trailhead_address].join(", ") %></span>
      <% end %>
    </div>
    <%= form.text_field :trailhead_address, placeholder: "Google maps link", class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div class="col-span-2">
    <div class="flex">
      <%= form.label :suggested_items, class: "mr-2" %>
      <% if @hike.errors[:suggested_items].any? %>
        <span class="text-red-500"><%= @hike.errors[:suggested_items].join(", ") %></span>
      <% end %>
    </div>
    <%= form.text_field :suggested_items, placeholder: "Comma-separated list of items", class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div class="col-span-2">
    <div class="flex">
      <%= form.label :notes, "Any other notes?", class: "mr-2" %>
      <% if @hike.errors[:notes].any? %>
        <span class="text-red-500"><%= @hike.errors[:notes].join(", ") %></span>
      <% end %>
    </div>
    <%= form.text_field :notes, class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div class="col-span-2">
    <div class="flex">
      <%= form.label :graphic, "Upload hike graphic", class: "mr-2" %>
      <% if @hike.errors[:graphic].any? %>
        <span class="text-red-500"><%= @hike.errors[:graphic].join(", ") %></span>
      <% end %>
    </div>
    <%= form.file_field :graphic, class: "shadow rounded-md border border-gray-200 w-full" %>
  </div>
  <div class="col-span-2">
    <div class="flex">
      <%= form.label :short_description, class: "mr-2" %>
      <% if @hike.errors[:short_description].any? %>
        <span class="text-red-500"><%= @hike.errors[:short_description].join(", ") %></span>
      <% end %>
    </div>
    <%= form.text_area :short_description, placeholder: "Short blurb for the hike (for Instagram and Discord)", class: "shadow rounded-md border border-gray-200 w-full min-h-64" %>
  </div>
  <div class="hidden">
    <%= form.label :status, "status" %>
    <%= form.hidden_field :status, "data-hike-target": "status", value: edit ? hike.status : "", id: "hike_status" %>
  </div>
  <div class="col-span-2">
    <%= form.submit "Save as draft", class: "cursor-pointer mt-4 rounded-lg py-3 px-5 bg-gray-200 hover:bg-gray-300 font-medium", data: { action: "click->hike#setStatusDraft" } %>
    <%= form.submit "Send for review", class: "cursor-pointer mt-4 rounded-lg py-3 px-5 bg-blue-200 hover:bg-blue-300 font-medium", data: { action: "click->hike#setStatusReview" } %>
    <% if @user.admin? %>
      <%= form.submit "Publish", class: "cursor-pointer mt-4 rounded-lg py-3 px-5 bg-green-200 hover:bg-green-300 font-medium", data: { action: "click->hike#confirmPublish click->hike#setStatusPublished"} %>
    <% end %>
    <% if edit %>
      <%= link_to "Cancel edit", hike_path(hike), method: :get, class: "mt-4 rounded-lg py-3 px-5 bg-red-200 hover:bg-red-300 font-medium" %>
    <% else %>
      <%= link_to "Cancel", hikes_path, class: "mt-4 rounded-lg py-3 px-5 bg-red-200 hover:bg-red-300 font-medium" %>
    <% end %>
  </div>
<% end %>

app/views/hikes/_hike_card.html.erb
<%= link_to hike_path(hike), class:"mx-auto max-w-md overflow-hidden rounded-lg bg-white shadow mb-4 hover:shadow-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-104" do %>
  <% if hike.graphic.attached? %>
    <%= image_tag hike.graphic, class:"aspect-video w-full object-cover", alt:hike.title %>
  <% else %>
    <div class="aspect-video w-full bg-red-200 text-center">Hike graphic hasn't been added</div>
  <% end %>
  <div class="p-4">
    <p class="mb-1 text-md text-primary-500"><%= hike.host.full_name %> • <time><%= hike.date if hike.datetime.present? %> • <%= hike.time if hike.datetime.present? %></time></p>
    <h3 class="text-xl font-medium text-gray-900"><%= hike.title %></h3>
    <p class="mt-1 text-gray-500"><%= hike.short_description %></p>
    <div class="mt-4 flex flex-wrap gap-2">
      <% if hike.length %>
        <span class="inline-flex items-center gap-1 rounded-full bg-violet-50 px-2 py-1 text-xs font-semibold text-violet-600"> Length: <%= hike.length %>mi</span>
      <% end %>
      <% if hike.elevation %>
        <span class="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-600"> Elevation: <%= hike.elevation.to_i %>ft</span>
      <% end %>
      <% if hike.difficulty %>
        <span class="inline-flex items-center gap-1 rounded-full bg-green-50 px-2 py-1 text-xs font-semibold text-green-600"> Difficulty: <%= HikesController::DIFFICULTY_MAPPING[hike.difficulty.to_i] %></span>
      <% end %>
      <% if hike.duration %>
        <span class="inline-flex items-center gap-1 rounded-full bg-yellow-50 px-2 py-1 text-xs font-semibold text-yellow-600"> Duration: <%= hike.duration.to_i / 60 %>h<%= ' ' + (hike.duration.to_i % 60).to_s + 'm' if hike.duration.to_i % 60 != 0 %></span>
      <% end %>
      <% if hike.route_type %>
        <span class="inline-flex items-center gap-1 rounded-full bg-red-50 px-2 py-1 text-xs font-semibold text-red-600"> Route: <%= hike.route_type  %></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/hikes/_mini_hike.html.erb
<%= link_to hike_path(hike), class:"mx-auto max-w-md overflow-hidden rounded-lg bg-white shadow mb-4 hover:shadow-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-104" do %>
  <%= image_tag hike.graphic_url, class:"aspect-video w-full object-cover", alt:hike.title %>
  <div class="p-4">
    <p class="mb-1 text-md text-primary-500"><%= hike.host.full_name %> • <time><%= hike.date.strftime('%B %d %A') %> • <%= hike.time.in_time_zone('Pacific Time (US & Canada)').strftime('%I:%M %p') %></time></p>
    <h3 class="text-xl font-medium text-gray-900"><%= hike.title %></h3>
    <p class="mt-1 text-gray-500"><%= hike.short_description %></p>
    <div class="mt-4 flex flex-wrap gap-2">
      <% if hike.length %>
        <span class="inline-flex items-center gap-1 rounded-full bg-violet-50 px-2 py-1 text-xs font-semibold text-violet-600"> Length: <%= hike.length %>mi</span>
      <% end %>
      <% if hike.elevation %>
        <span class="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-600"> Elevation: <%= hike.elevation %>ft</span>
      <% end %>
      <% if hike.difficulty %>
        <span class="inline-flex items-center gap-1 rounded-full bg-green-50 px-2 py-1 text-xs font-semibold text-green-600"> Difficulty: <%= HikesController::DIFFICULTY_MAPPING[hike.difficulty.to_i] %></span>
      <% end %>
      <% if hike.duration %>
        <span class="inline-flex items-center gap-1 rounded-full bg-yellow-50 px-2 py-1 text-xs font-semibold text-yellow-600"> Duration: <%= hike.duration / 60 %>h<%= ' ' + (hike.duration % 60).to_s + 'm' if hike.duration % 60 != 0 %></span>
      <% end %>
      <% if hike.route_type %>
        <span class="inline-flex items-center gap-1 rounded-full bg-red-50 px-2 py-1 text-xs font-semibold text-red-600"> Route: <%= hike.route_type  %></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/hikes/_subscription.html.erb
<%= turbo_frame_tag "new_hike_subscription" do %>
  <div class="my-6 text-center">
    <% if @user.subscribed?(hike) %>
      <h2>You are subsribed to receive notifications when a new car is added to this hike.</h2>
      <%= button_to "Unsubscribe", subscribe_hike_path(hike), method: :delete, class: "rounded-lg py-3 px-5 bg-red-100 hover:bg-red-200 inline-block font-medium" %>
    <% else %>
      <% if @user.allowed_notifications? %>
        <h2>Subscribe to receive notifications when a new car is added to this hike.</h2>
        <% if @session.push_endpoint.nil? %>
          <h2> Notifications are not enabled on this device, however another device you use has notifications enabled. </h2>
        <% end %>
        <%= button_to "Subscribe", subscribe_hike_path(hike), method: :post, class: "rounded-lg py-3 px-5 bg-blue-100 hover:bg-blue-200 inline-block font-medium" %>
      <% else %>
        <h2>Please allow notifications to be able to receive them when a new car is added to this hike.</h2>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/hikes/edit.html.erb
<div class="w-full h-full lg:max-w-4xl mx-auto my-2 rounded-lg p-6 shadow-lg">
  <h1 class="font-bold text-2xl">Host a hike</h1>
  <%= render "form", hike: @hike, edit: true %>
</div>

app/views/hikes/index.html.erb
<div class="w-11/12 mx-auto">
  <div class="mt-4">
    <h1 class="font-bold text-2xl mb-4 text-center">Upcoming Hikes</h1>
    <%#= link_to "New hike", new_hike_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <div id="upcoming_hikes" class="min-w-full flex flex-wrap gap-5">
      <% if @upcoming_hikes.empty? %>
        <p class="text-gray-500">No upcoming hikes</p>
      <% else %>
        <% @upcoming_hikes.each do |hike| %>
          <%= render "hike_card", hike: hike %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="mt-4">
    <h1 class="font-bold text-2xl mb-4 text-center">Past Hikes</h1>
    <%#= link_to "New hike", new_hike_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <div id="past_hikes" class="min-w-full gap-5">
      <% if @past_hikes.empty? %>
        <p class="text-gray-500">No past hikes</p>
      <% else %>
        <div class="w-full flex flex-wrap">
          <% @past_hikes.each do |hike| %>
            <%= render "hike_card", hike: hike %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="flex justify-center mb-6">
      <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
    </div>
  </div>
</div>

app/views/hikes/new.html.erb
<div class="w-full h-full lg:max-w-4xl mx-auto my-2 rounded-lg p-6 shadow-lg">
  <h1 class="font-bold text-2xl">Host a hike</h1>
  <%= render "form", hike: @hike, edit: false %>
</div>

app/views/hikes/show.html.erb
<% if @user.admin? || @user.host?(@hike) %>
  <section class="mx-auto xl:w-2/3 w-full flex justify-center">
    <%= link_to "Edit hike", edit_hike_path(@hike), class: "mt-6 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
    <%= link_to "Delete hike", hike_path(@hike), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this hike?"}, class: "inline-block ml-2 mt-6 rounded-lg py-3 px-5 bg-red-100 hover:bg-red-200 font-medium" %>
  </section>
<% end %>
<%= render @hike %>
<section id="hike_cars" class="md:w-2/3 mx-auto my-12 block" data-controller="hike_cars">
  <% if @hike.hike_cars.any? %>
    <h2 class="font-bold text-3xl text-center"> Vehicles </h2>
    <%= render @hike.hike_cars %>
  <% end %>
</section>
<% if @hike.datetime.present? && @hike.datetime > Date.today %>
  <%= turbo_frame_tag "new_hike_car", src: new_hike_hike_car_path(@hike), target: "_top" %>
  <%= turbo_frame_tag "new_hike_subscription", src: subscribe_hike_path(@hike), method: :get %>
<% end %>