config/routes.rb
Rails.application.routes.draw do
  resources :hikes do
    member do
      match 'subscribe', to: 'hikes#subscribe', via: %i[get post delete]
    end
    resources :hike_cars, shallow: true, except: %i[index] do
      resources :hike_participants, shallow: true, except: %i[index]
    end
  end
  get 'hike_details' => 'hikes#hike_details', as: :get_hike_details

  resource :user, except: %i[new create] do
    resource :waiver, only: %i[new create show]
    resource :session, only: %i[new create update destroy]
  end
  resolve('User') { [:user] }

  scope :user do
    resources :cars, except: %i[index]
  end

  get 'auth/google_oauth2/callback' => 'sessions#create'
  get 'help' => 'static#help'
  get "up" => "rails/health#show", as: :rails_health_check

  root "dashboard#index"
end

app/models/hike_car.rb
class HikeCar < ApplicationRecord
  belongs_to :hike
  belongs_to :car
  has_one :driver, through: :car, source: :user
  has_many :participants, class_name: 'HikeParticipant', dependent: :destroy
  store :metadata, accessors: %i[spots_available pickup_time pickup_address compensation note], coder: JSON

  def spot_available?
    participants.length < spots_available.to_i
  end
end

app/controllers/hike_cars_controller.rb
class HikeCarsController < ApplicationController
  before_action :set_hike, only: %i[new create]
  before_action :set_hike_car, only: %i[show edit update destroy]

  def show
    @hike_car = HikeCar.find(params[:id])
  end

  def new
    @hike_car = @hike.hike_cars.new
  end

  def edit
  end

  def create
    @hike_car = @hike.hike_cars.create!(hike_car_params)
    hike_car_notification

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @hike, notice: "Car has been added to the hike" }
    end
  end

  def update
    if @hike_car.update(hike_car_params)
      redirect_to hike_car_url(@hike_car), notice: "Hike car was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @hike_car.destroy!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @hike, notice: "Successfully removed car from the hike" }
    end
  end

  private

  def set_hike
    @hike = Hike.find(params[:hike_id])
  end

  def set_hike_car
    @hike_car = HikeCar.find(params[:id])
  end

  def hike_car_params
    params.require(:hike_car).permit(:hike_id, :car_id, :spots_available, :pickup_time, :pickup_address, :compensation,
                                     :note)
  end

  def hike_car_notification
    title = "New car added"
    body = "A new car has been added to the #{@hike.title} hike!"
    icon = @hike.graphic.attached? ? url_for(@hike.graphic) : '/assets/hiking_logo.svg'
    link = hike_url(@hike)

    subscribed_users = User.find(@hike.subscribers)
    notify_users(subscribed_users, title, body, icon, link)
  end
end

app/helpers/hike_cars_helper.rb
module HikeCarsHelper
end

app/views/hike_cars/_form.html.erb
<%= form_with model: [ @hike, @hike_car ], class: "mt-4 rounded-lg justify-center flex mx-auto" do |form| %>
  <table class="w-full justify-center bg-white text-sm text-center text-gray-500" cellspacing="0">
    <thead class="bg-gray-50 text-gray-900 font-medium">
      <tr class="px-4 xl:grid xl:grid-cols-11 py-4">
        <th scope="col" class="hidden xl:block xl:col-span-2">Car</th>
        <th scope="col" class="hidden xl:block">Spots</th>
        <th scope="col" class="hidden xl:block xl:col-span-2">Pickup@Time</th>
        <th scope="col" class="hidden xl:block xl:col-span-2">Pickup Address</th>
        <th scope="col" class="hidden xl:block">Compensation</th>
        <th scope="col" class="hidden xl:block xl:col-span-2">Note</th>
        <th scope="col" class="hidden xl:block"></th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-100 border-t border-gray-100">
      <tr class="hover:bg-gray-50 xl:grid xl:grid-cols-11 xl:gap-2 py-4 font-normal text-gray-900">
        <td class="py-2 grid grid-cols-3 gap-3 xl:flex xl:gap-0 xl:col-span-2">
          <%= form.label :car_id, class: "flex font-medium justify-center items-center xl:hidden" %>
          <%= form.select :car_id, @user.cars.map{ |c| [c.make + ' ' + c.model, c.id] }, {}, { :class =>"col-span-2 xl:w-full rounded-md border-gray-300 shadow-sm focus:border-primary-300 focus:ring focus:ring-primary-200 focus:ring-opacity-50 disabled:cursor-not-allowed disabled:bg-gray-50" } %>
        </td>
        <td class="py-2 grid grid-cols-3 gap-3 xl:flex xl:gap-0">
          <%= form.label :spots_available, "Spots", class: "flex font-medium justify-center items-center xl:hidden" %>
          <%= form.number_field :spots_available, class:"col-span-2 xl:w-full rounded-md border-gray-300 shadow-sm focus:border-primary-400 focus:ring focus:ring-primary-200 focus:ring-opacity-50 disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500 text-sm" %>
        </td>
        <td class="py-2 grid grid-cols-3 gap-3 xl:flex xl:gap-0 xl:col-span-2">
          <%= form.label :pickup_time, "Pickup@ Time", class: "flex font-medium justify-center items-center xl:hidden" %>
          <%= form.text_field :pickup_time, placeholder: "PC Loop@9:30AM", class:"col-span-2 xl:w-full rounded-md border-gray-300 shadow-sm focus:border-primary-400 focus:ring focus:ring-primary-200 focus:ring-opacity-50 disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500 text-sm"%>
        </td>
        <td class="py-2 grid grid-cols-3 gap-3 xl:flex xl:gap-0 xl:col-span-2">
          <%= form.label :pickup_address, "Pickup Address", class: "flex font-medium justify-center items-center xl:hidden" %>
          <%= form.text_field :pickup_address, placeholder: "Google maps link", class:"col-span-2 xl:w-full rounded-md border-gray-300 shadow-sm focus:border-primary-400 focus:ring focus:ring-primary-200 focus:ring-opacity-50 disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500 text-sm"%>
        </td>
        <td class="py-2 grid grid-cols-3 gap-3 xl:flex xl:gap-0">
          <%= form.label :compensation, class: "flex font-medium justify-center items-center xl:hidden" %>
          <%= form.number_field :compensation, step: 0.5, placeholder: "$/person", class:"col-span-2 xl:w-full rounded-md border-gray-300 shadow-sm focus:border-primary-400 focus:ring focus:ring-primary-200 focus:ring-opacity-50 disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500 text-sm"%>
        </td>
        <td class="py-2 grid grid-cols-3 gap-3 xl:flex xl:gap-0 xl:col-span-2">
          <%= form.label :note, class: "flex font-medium justify-center items-center xl:hidden" %>
          <%= form.text_field :note, class:"col-span-2 xl:w-full rounded-md border-gray-300 shadow-sm focus:border-primary-400 focus:ring focus:ring-primary-200 focus:ring-opacity-50 disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-500 text-sm", placeholder: "Note for passengers"%>
        </td>
        <td class="py-2 h-16 grid grid-cols-3 gap-3 xl:flex xl:gap-0">
          <% if edit %>
            <%= form.submit "Update", class: "col-start-2 col-span-2 xl:w-full rounded-lg px-2 bg-gray-500 hover:bg-gray-600 text-white cursor-pointer" %>
          <% else %>
            <%= form.submit "Add car", class: "col-start-2 col-span-2 xl:w-full rounded-lg px-2 bg-blue-500 hover:bg-blue-600 text-white cursor-pointer" %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/hike_cars/_hike_car.html.erb
<%= turbo_frame_tag dom_id(hike_car) do %>
  <div class="mx-4 my-6 overflow-hidden rounded-lg border border-gray-200 shadow-md">
    <div class="table w-full items-center justify-center bg-white text-sm text-center text-gray-500">
      <div class="table-header-group bg-gray-50 text-gray-900 font-medium">
        <div class="px-4 relative grid grid-cols-2 xl:grid-cols-4">
          <div class="py-2 flex justify-center gap-3 items-center">
            <div class="flex-shrink-0">
              <%= render "avatar", user: hike_car.car.user %>
            </div>
            <div class="flex flex-col items-center w-full">
              <div class="text-gray-700"><%= hike_car.car.user.preferred_name.present? ? hike_car.car.user.preferred_name : hike_car.car.user.full_name %></div>
              <%= link_to number_to_phone(hike_car.car.user.phone_no, area_code: true), "tel:#{hike_car.car.user.phone_no}", class: "text-primary-500 text-xs" %>
            </div>
          </div>
          <div class="py-2 flex justify-center items-center">
            <div>
              <div class="text-gray-700"><%= hike_car.car.make + ' ' + hike_car.car.model %></div>
              <div class="text-gray-400"><%= hike_car.car.color %></div>
            </div>
          </div>
          <div class="py-2 flex justify-center items-center">
            <div>
              <%= link_to hike_car.pickup_time.split('@').first, hike_car.pickup_address, class: "text-primary-500" %>
              <div class="text-gray-400">@<%= hike_car.pickup_time.split('@').second %></div>
            </div>
          </div>
          <div class="py-2 flex w-full justify-center items-center">
            <div>
              <div class="text-gray-700"><%= hike_car.spots_available %> spots</div>
              <div class="text-gray-400"><%= number_with_precision(hike_car.compensation, precision: 2) %>$ per person</div>
            </div>
          </div>
          <div class="absolute right-4 bottom-12 xl:top-3 py-2">
            <% if @user.car_driver?(hike_car) %>
              <div class="flex gap-1">
                <%= link_to edit_hike_car_path(hike_car), "x-data":"{ tooltip: 'Edit' }" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="blue" class="h-5 w-5 cursor-pointer text-secondary-500" x-tooltip="tooltip">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
                  </svg>
                <% end %>
                <%= link_to hike_car_path(hike_car), data: {turbo_method: :delete, turbo_frame: "_top", turbo_confirm: "Are you sure you want to remove your car from the hike?"}, "x-data":"{ tooltip: 'Delete' }" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="red" class="h-5 w-5 cursor-pointer text-secondary-500" x-tooltip="tooltip">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                  </svg>
                <% end %>
              </div>
            <% elsif hike_car.note.present? %>
              <div class="flex" x-data="{ tooltip: '<%= hike_car.note %>' }">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="green" class="h-6 w-6 cursor-pointer text-secondary-500" x-tooltip.animation.scale="tooltip">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
                </svg>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div id="<%= dom_id(hike_car) %>_participants" class="table-row-group divide-y divide-gray-100 border-t border-gray-100">
        <%= render hike_car.participants %>
      </div>
      <div class="table-footer-group bg-blue-50 text-blue-900 font-medium">
        <%= turbo_frame_tag "new_" + dom_id(hike_car) + "_participant", src: new_hike_car_hike_participant_path(hike_car), target: "_top" %>
      </div>
    </div>
  </div>
<% end %>

app/views/hike_cars/create.turbo_stream.erb
<%= turbo_stream.append "hike_cars", @hike_car %>
<%= turbo_stream.update "new_hike_car", "" %>

app/views/hike_cars/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@hike_car) %>
<%= turbo_stream.replace "new_hike_car" do %>
  <%= turbo_frame_tag "new_hike_car", src: new_hike_hike_car_path(@hike_car.hike), target: "_top" %>
<% end %>

app/views/hike_cars/edit.html.erb
<%= turbo_frame_tag dom_id(@hike_car), target: "_top" do %>
  <h2 class="font-semibold mt-6 text-2xl text-center"> Edit your car details </h2>
  <%= render "form", hike_car: @hike_car, edit: true %>
  <div id="<%= dom_id(@hike_car) %>_participants" class="w-full items-center justify-center bg-white text-sm text-center text-gray-500">
    <%= render @hike_car.participants %>
  </div>
<% end %>

app/views/hike_cars/new.html.erb
<%= turbo_frame_tag "new_hike_car", target: "_top" do %>
  <section class="my-8 px-4 mx-auto xl:w-2/3 w-full">
    <% if @user.cars.empty? %>
      <div class="flex my-5 rounded-md bg-yellow-50 p-4 text-sm text-yellow-500" x-cloak x-show="showAlert" x-data="{ showAlert: true }">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="mr-3 h-5 w-5 flex-shrink-0">
          <path fill-rule="evenodd" d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495zM10 5a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 0110 5zm0 9a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
        </svg>
        <div>To include your car for the hike, please register it in your profile first. <a href="<%= user_path %>" class="underline">Click here to add a car</a>.</div>
        <button class="ml-auto" x-on:click="showAlert = false">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="h-5 w-5">
            <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
          </svg>
        </button>
      </div>
    <% elsif @user.hike_cars.exists?(hike_id: @hike.id) %>
      <!--<div class="flex my-5 rounded-md bg-yellow-50 p-4 text-sm text-yellow-500" x-cloak x-show="showAlert" x-data="{ showAlert: true }">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="mr-3 h-5 w-5 flex-shrink-0">
          <path fill-rule="evenodd" d="M8.485 2.495c.673-1.167 2.357-1.167 3.03 0l6.28 10.875c.673 1.167-.17 2.625-1.516 2.625H3.72c-1.347 0-2.189-1.458-1.515-2.625L8.485 2.495zM10 5a.75.75 0 01.75.75v3.5a.75.75 0 01-1.5 0v-3.5A.75.75 0 0110 5zm0 9a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
        </svg>
        <div>You have already added a car.</div>
        <button class="ml-auto" x-on:click="showAlert = false">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="h-5 w-5">
            <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
          </svg>
        </button>
      </div>-->
    <% else %>
      <h2 class="font-semibold mt-6 text-2xl text-center"> Add your car </h2>
      <%= render "form", hike_car: @hike_car, edit: false %>
    <% end %>
  </section>
<% end %>

app/views/hike_cars/show.html.erb
<div class="mx-auto items-center justify-center w-full flex">
  <%= render @hike_car %>
</div>